create extension if not exists "pgcrypto";

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    phone_number text not null unique,
    created_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.farmlands (
    id uuid primary key default gen_random_uuid(),
    user_id bigint not null references public.users(id) on delete cascade,
    name text not null,
    crops jsonb not null default '[]'::jsonb,
    soil_type text,
    location_lat double precision not null,
    location_lng double precision not null,
    boundary_points jsonb not null default '[]'::jsonb,
    heat_index double precision not null default 0,
    created_at bigint not null default (extract(epoch from now()) * 1000)::bigint,
    updated_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

alter table public.farmlands
    add column if not exists boundary_points jsonb not null default '[]'::jsonb,
    add column if not exists heat_index double precision not null default 0;

create table if not exists public.pest_alerts (
    id bigint generated by default as identity primary key,
    crop_name text not null,
    pest_type text not null,
    severity text not null check (severity in ('Low', 'Medium', 'High')),
    location_lat double precision not null,
    location_lng double precision not null,
    timestamp bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create or replace function public.set_current_epoch_millis()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = (extract(epoch from now()) * 1000)::bigint;
    return new;
end;
$$;

drop trigger if exists farmlands_set_updated_at on public.farmlands;
create trigger farmlands_set_updated_at
before update on public.farmlands
for each row execute function public.set_current_epoch_millis();

create index if not exists users_phone_number_idx on public.users(phone_number);
create index if not exists farmlands_user_id_idx on public.farmlands(user_id);
create index if not exists pest_alerts_timestamp_idx on public.pest_alerts(timestamp desc);
create index if not exists pest_alerts_pest_type_idx on public.pest_alerts(lower(pest_type));

alter table public.users enable row level security;
alter table public.farmlands enable row level security;
alter table public.pest_alerts enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.users to anon, authenticated;
grant select, insert, update, delete on table public.farmlands to anon, authenticated;
grant select, insert on table public.pest_alerts to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "Public users can be read for phone OTP demo" on public.users;
create policy "Public users can be read for phone OTP demo"
on public.users for select
to anon, authenticated
using (true);

drop policy if exists "Public users can register for phone OTP demo" on public.users;
create policy "Public users can register for phone OTP demo"
on public.users for insert
to anon, authenticated
with check (true);

drop policy if exists "Public farmlands can be read for hackathon demo" on public.farmlands;
create policy "Public farmlands can be read for hackathon demo"
on public.farmlands for select
to anon, authenticated
using (true);

drop policy if exists "Public farmlands can be inserted for hackathon demo" on public.farmlands;
create policy "Public farmlands can be inserted for hackathon demo"
on public.farmlands for insert
to anon, authenticated
with check (true);

drop policy if exists "Public farmlands can be updated for hackathon demo" on public.farmlands;
create policy "Public farmlands can be updated for hackathon demo"
on public.farmlands for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public farmlands can be deleted for hackathon demo" on public.farmlands;
create policy "Public farmlands can be deleted for hackathon demo"
on public.farmlands for delete
to anon, authenticated
using (true);

drop policy if exists "Public alerts can be read" on public.pest_alerts;
create policy "Public alerts can be read"
on public.pest_alerts for select
to anon, authenticated
using (true);

drop policy if exists "Public alerts can be posted" on public.pest_alerts;
create policy "Public alerts can be posted"
on public.pest_alerts for insert
to anon, authenticated
with check (true);

notify pgrst, 'reload schema';
