create table if not exists public.account_deletion_feedback (
    id bigint generated by default as identity primary key,
    user_id bigint,
    name text,
    phone_number text,
    reason text not null,
    created_at timestamptz not null default now()
);

alter table public.account_deletion_feedback enable row level security;

grant select, insert on table public.account_deletion_feedback to anon, authenticated;
grant update, delete on table public.users to anon, authenticated;

drop policy if exists "Public deletion feedback can be saved" on public.account_deletion_feedback;
create policy "Public deletion feedback can be saved"
on public.account_deletion_feedback for insert
to anon, authenticated
with check (true);

drop policy if exists "Public deletion feedback can be read for demo" on public.account_deletion_feedback;
create policy "Public deletion feedback can be read for demo"
on public.account_deletion_feedback for select
to anon, authenticated
using (true);

drop policy if exists "Public users can update profile for phone OTP demo" on public.users;
create policy "Public users can update profile for phone OTP demo"
on public.users for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public users can delete account for phone OTP demo" on public.users;
create policy "Public users can delete account for phone OTP demo"
on public.users for delete
to anon, authenticated
using (true);

notify pgrst, 'reload schema';
